### ISSUE TITLE
TODO(ci): automatically create draft releases on v*.* tag push

### ISSUE THREAD

**Issue by akavel** [akavel/mana#10]
- [ ] when a `v*` tag is pushed - `on: push: tags: [ 'v*.*' ]` ([via](https://github.com/orgs/community/discussions/45144))
- [ ] assert that `v...` in Cargo.toml matches with the tag; fail build if it doesn't
- [ ] create new draft release ([hints](https://www.howtogeek.com/devops/how-to-automatically-publish-github-releases-from-git-tags/)) - only if it doesn't exist yet ([hints](https://www.codingwithcalvin.net/git-tag-based-released-process-using-github-actions/))
- [ ] build with --release mode for multiple targets: at least windows-amd64, linux-amd64, darwin-mX, darwin-amd64
- [ ] upload mana binaries, with target included in name, as release asset binaries
