### ISSUE TITLE
TODO: zeroinstall - track manifest-digest on Windows

### ISSUE THREAD

**Issue by akavel** [akavel/mana#14]
Goal: precisely track installed versions of 0install apps

- [ ] query: "installed versions" - read names of dirs (corresponding to hash strings) in:
  - [ ] `%PROGRAMDATA%\0install.net\implementations\`
  - [ ] `%LOCALAPPDATA%\0install.net\implementations\`
- [ ] query: translate "installed versions" hashes into human-readable URLs + version IDs
  - [ ] read files from `%LOCALAPPDATA%\0install.net\interfaces\`
  - [ ] parse `<implementation version=“25.6.2” id=“sha256new_APRH6BPECHOVOU2E3E65NQDDTTUXVS63A7RRXQ7JSY3LHR2GLONA”>` nodes from those files, giving version info + URL from hash
  - [ ] emit retrieved versions + URLs + hashes into shadow XMLs
- [ ] apply: ...?
