### ISSUE TITLE
TODO: spawned effectors

### ISSUE THREAD

**Issue by akavel** [akavel/mana#5]
steps proposed:
 - [x] implement subcommand `effector ssh` etc.
   - can test it by hand initially
   - [x] `zeroinstall` (easiest - args already known, no need to worry about Lua)
   - [x] `ssh`
   - [x] `winfs`
   - [x] `winhome`
   - [x] `winpath`
 - [x] expand leading `*ssh` etc. in nickel effectors into `$ARGV[0] effector ssh` etc.
 - [x] spawn effectors early as subprocesses, keep them running and pipe data in/out over lifetime of mana process
 - [x] \[opt] make lua53 effector, for running stuff easily via Lua - builtin Lua effectors would have shortcut without lua53 as well
