### ISSUE TITLE
TODO: handling of encrypted files/data

### ISSUE THREAD

**Issue by akavel** [akavel/mana#8]
Use cases:
 - [ ] 0install pgp secrets synced on Windows machines
 - [ ] putty sessions keys synced
   - [ ] also putty sessions, probably via registry
     - [ ] check if putty sessions are stored in registry, or elsewhere

Some inspiration:
 - [ryantm/agenix](https://github.com/ryantm/agenix) (see also [on nixos.wiki](https://nixos.wiki/wiki/Agenix))
